Pass through skipDuplicate
HaaLeo/publish-vscode-extension pull request #39
Opened 2023-05-24 11:46 UTC by PieterjanDeClippel

# Summary

Pass through the `skipDuplicate` option to the `@vscode/vsce` methods.

# Changes

* Add `skipDuplicate` to the options
* Filter out `skipDuplicate` and pass to the `@vscode/vsce` `publishVSIX` method
* main: Read `skipDuplicate` from the Github Actions workflow step inputs

# Related Issues

Fixes #

2023-05-24 22:56 UTC, PieterjanDeClippel commented
@HaaLeo

2023-06-24 17:05 UTC, HaaLeo requested changes

2023-06-24 17:05 UTC, HaaLeo commented on ThirdPartyNotices.txt
> -THIRD-PARTY SOFTWARE NOTICES AND INFORMATION
Can you pls undo the changes on this file? they shouldn't necessary

2023-06-24 17:05 UTC, HaaLeo commented on src/publish.ts
> +    const { baseContentUrl, baseImagesUrl, pat, yarn: useYarn, noVerify, dependencies, skipDuplicate } = { ...options };
Can you extend the tests pls to check for the `skipDuplicate` property?

2023-07-05 21:33 UTC, HaaLeo commented
I had some spare time to add the feature myself. Nevertheless thank you a lot for your contribution. It feels horrible to close an unmerged PR

2023-07-05 21:33 UTC, closed without merging