handle open-vsx publish errors
HaaLeo/publish-vscode-extension pull request #41
Opened 2023-06-11 10:14 UTC by VladBrok

# Summary
handle open-vsx publish errors

# Changes
* add code for handling open-vsx publish errors

# Related Issues
Fixes #40

2023-06-24 17:08 UTC, HaaLeo requested changes

2023-06-24 17:08 UTC, HaaLeo commented on ThirdPartyNotices.txt
> -THIRD-PARTY SOFTWARE NOTICES AND INFORMATION
Can you pls undo the changes on this file? The shouldn't be necessary

2023-06-24 17:08 UTC, HaaLeo commented on src/publish.ts
> +        const results = await ovsxPublish(options);
Can you pls add a unit test for your changes?

2023-06-25 07:28 UTC, VladBrok commented
@HaaLeo, done

2023-07-05 20:46 UTC, merged